source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'ProjectOxfordFace_Example' do
	pod 'ProjectOxfordFace', :path => '../'
    pod 'MobileCenter'

	target 'ProjectOxfordFace_Tests' do
		inherit! :search_paths

	end
end
