platform :ios, '8.0'
use_frameworks!

target 'ProjectOxfordFace_Example' do
    pod 'ProjectOxfordFace', :path => '../'

    target 'ProjectOxfordFace_Tests' do
        inherit! :search_paths

    end
end
